/admin/dashboard:
  controller: AdminController
  method: indexAction

/admin/sign-up:
  controller: AdminController
  method: signUpAction

/admin/login:
  controller: AdminController
  method: loginAction

/admin/logout:
  controller: AdminController
  method: logoutAction

/admin/add-post:
  controller: AdminController
  method: addPostAction

/admin/add-category:
  controller: AdminController
  method: addCategoryAction


#/admin/add-category:
#  controller: AdminController
#  method:

#/deneme:
#  controller: DefaultController
#  method: indexAction
#
#/blog/list:
#    controller: DefaultController
#    method: indexAction
#
#
#/admin/blog/{slug}:
#    controller: AdminController
#    method: ali
#    params: {
#      '{slug}': '([0-9a-zA-Z\-]+)'
#    }
#
#
#/blog/list/{id}/update/{slug}:
#    controller: DefaultController
#    method: updateAction
#    params: {
#      '{id}': (\d+),
#      '{slug}': '([0-9a-zA-Z\-]+)$'
#    }




