/:
  controller: App\Controller\Storefront\BlogController
  method: index

/blog-detail/{id}:
  controller: App\Controller\Storefront\BlogController
  method: detailAction
  params: {
      '{id}': (\d+)
  }

/login:
  controller: App\Controller\Storefront\AdminController
  method: loginAction

/logout:
  controller: App\Controller\Storefront\AdminController
  method: logoutAction

/sign-up:
  controller: App\Controller\Storefront\AdminController
  method: signUpAction

/category/{slug}:
  controller: App\Controller\Storefront\CategoryController
  method: getAction
  params: {
      '{slug}': ([0-9a-zA-Z\-]+)
  }

/search-results:
  controller: App\Controller\Storefront\BlogController
  method: searchAction



/admin/dashboard:
  controller: App\Controller\Admin\AdminController
  method: indexAction

/admin/sign-up:
  controller: App\Controller\Admin\AdminController
  method: signUpAction

/admin/login:
  controller: App\Controller\Admin\AdminController
  method: loginAction

/admin/logout:
  controller: App\Controller\Admin\AdminController
  method: logoutAction

/admin/add-blog:
  controller: App\Controller\Admin\BlogController
  method: addAction

/admin/add-category:
  controller: App\Controller\Admin\CategoryController
  method: addAction

/admin/blog-list:
  controller: App\Controller\Admin\BlogController
  method: getAction

/admin/blog-delete/{id}:
  controller: App\Controller\Admin\BlogController
  method: deleteAction
  params: {
    '{id}': (\d+)
  }

/admin/blog-detail/{id}:
  controller: App\Controller\Admin\BlogController
  method: detailAction
  params: {
      '{id}': (\d+)
  }

/admin/blog-update/{id}:
  controller: App\Controller\Admin\BlogController
  method: updateAction
  params: {
      '{id}':(\d+)
  }





#/admin/add-category:
#  controller: AdminController
#  method:

#/deneme:
#  controller: DefaultController
#  method: indexAction
#
#/blog/list:
#    controller: DefaultController
#    method: indexAction
#
#
#/admin/blog/{slug}:
#    controller: AdminController
#    method: ali
#    params: {
#      '{slug}': '([0-9a-zA-Z\-]+)'
#    }
#
#
#/blog/list/{id}/update/{slug}:
#    controller: DefaultController
#    method: updateAction
#    params: {
#      '{id}': (\d+),
#      '{slug}': '([0-9a-zA-Z\-]+)$'
#    }




